database:
  driver: mysql
  connection: daedokim:dhkswnd!233@tcp(daedokim.ciqpnaygskyd.ap-northeast-2.rds.amazonaws.com:3306)/daedokim?parseTime=true&charset=utf8
  debug: true

host: 0.0.0.0
port: :8080
